// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyTLUServer.Infrastructure.Data;

#nullable disable

namespace MyTLUServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251031161049_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyTLUServer.Domain.Models.AttendanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttendanceStatus")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("attendance_status");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("check_in_time");

                    b.Property<int?>("ClassSessionId")
                        .HasColumnType("int")
                        .HasColumnName("class_session_id");

                    b.Property<string>("Method")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("method");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<string>("StudentCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("student_code");

                    b.HasKey("Id")
                        .HasName("PK__attendan__3213E83FE14295E5");

                    b.HasIndex("ClassSessionId");

                    b.HasIndex("StudentCode");

                    b.ToTable("attendance_records");
                });

            modelBuilder.Entity("MyTLUServer.Domain.Models.Class", b =>
                {
                    b.Property<string>("ClassCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("class_code");

                    b.Property<string>("AcademicYear")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("academic_year");

                    b.Property<DateOnly?>("ClassEndDate")
                        .HasColumnType("date")
                        .HasColumnName("class_end_date");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("class_name");

                    b.Property<DateOnly?>("ClassStartDate")
                        .HasColumnType("date")
                        .HasColumnName("class_start_date");

                    b.Property<string>("ClassStatus")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("class_status");

                    b.Property<string>("ClassType")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("class_type");

                    b.Property<string>("DefaultLocation")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("default_location");

                    b.Property<string>("LecturerCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("lecturer_code");

                    b.Property<int?>("MaxStudents")
                        .HasColumnType("int")
                        .HasColumnName("max_students");

                    b.Property<string>("ScheduleSummary")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("schedule_summary");

                    b.Property<string>("Semester")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("semester");

                    b.Property<string>("SubjectCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("subject_code");

                    b.HasKey("ClassCode")
                        .HasName("PK__classes__0AF9B2E5773F8499");

                    b.HasIndex("LecturerCode");

                    b.HasIndex("SubjectCode");

                    b.ToTable("classes");
                });

            modelBuilder.Entity("MyTLUServer.Domain.Models.ClassSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("class_code");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<string>("QrCodeData")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("qr_code_data");

                    b.Property<DateOnly?>("SessionDate")
                        .HasColumnType("date")
                        .HasColumnName("session_date");

                    b.Property<string>("SessionLocation")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("session_location");

                    b.Property<string>("SessionStatus")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("session_status");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PK__class_se__3213E83F0228B959");

                    b.HasIndex("ClassCode");

                    b.ToTable("class_sessions");
                });

            modelBuilder.Entity("MyTLUServer.Domain.Models.Curriculum", b =>
                {
                    b.Property<string>("MajorCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("major_code");

                    b.Property<string>("SubjectCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("subject_code");

                    b.Property<string>("ProgramStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("active")
                        .HasColumnName("program_status");

                    b.Property<bool?>("Required")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("required");

                    b.HasKey("MajorCode", "SubjectCode")
                        .HasName("PK__curricul__0199E1324817072C");

                    b.HasIndex("SubjectCode");

                    b.ToTable("curriculum");
                });

            modelBuilder.Entity("MyTLUServer.Domain.Models.Department", b =>
                {
                    b.Property<string>("DeptCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("dept_code");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("dept_name");

                    b.Property<string>("FacultyCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("faculty_code");

                    b.HasKey("DeptCode")
                        .HasName("PK__departme__799C94D4FF2F2EB4");

                    b.HasIndex("FacultyCode");

                    b.HasIndex(new[] { "DeptName" }, "UQ__departme__C7D39AE14318276A")
                        .IsUnique();

                    b.ToTable("departments");
                });

            modelBuilder.Entity("MyTLUServer.Domain.Models.Enrollment", b =>
                {
                    b.Property<string>("StudentCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("student_code");

                    b.Property<string>("ClassCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("class_code");

                    b.Property<string>("EnrollmentStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("enrolled")
                        .HasColumnName("enrollment_status");

                    b.HasKey("StudentCode", "ClassCode")
                        .HasName("PK__enrollme__2D5CA76AE3AF2049");

                    b.HasIndex("ClassCode");

                    b.ToTable("enrollments");
                });

            modelBuilder.Entity("MyTLUServer.Domain.Models.FaceDatum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FaceEmbedding")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("face_embedding");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("image_path");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<string>("StudentCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("student_code");

                    b.Property<string>("UploadStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("upload_status");

                    b.Property<DateTime?>("UploadedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id")
                        .HasName("PK__face_dat__3213E83FCA0C7994");

                    b.HasIndex("StudentCode");

                    b.ToTable("face_data");
                });

            modelBuilder.Entity("MyTLUServer.Domain.Models.Faculty", b =>
                {
                    b.Property<string>("FacultyCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("faculty_code");

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("faculty_name");

                    b.Property<string>("OfficeLocation")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("office_location");

                    b.HasKey("FacultyCode")
                        .HasName("PK__facultie__8492FC161C03FCE3");

                    b.HasIndex(new[] { "FacultyName" }, "UQ__facultie__22BC13FB33FEDEFA")
                        .IsUnique();

                    b.ToTable("faculties");
                });

            modelBuilder.Entity("MyTLUServer.Domain.Models.Lecturer", b =>
                {
                    b.Property<string>("LecturerCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("lecturer_code");

                    b.Property<string>("AcademicRank")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("academic_rank");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("avatar_url");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Degree")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("degree");

                    b.Property<string>("DeptCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("dept_code");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("gender");

                    b.Property<string>("OfficeLocation")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("office_location");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.HasKey("LecturerCode")
                        .HasName("PK__lecturer__14870CE86B1976E8");

                    b.HasIndex("DeptCode");

                    b.ToTable("lecturers");
                });

            modelBuilder.Entity("MyTLUServer.Domain.Models.Login", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("active")
                        .HasColumnName("account_status");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("LoginPosition")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("updated_pos");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("user_role");

                    b.HasKey("Username")
                        .HasName("PK__login__F3DBC5739DC1CB05");

                    b.HasIndex(new[] { "Email" }, "UQ__login__AB6E6164EEF18533")
                        .IsUnique();

                    b.ToTable("login");
                });

            modelBuilder.Entity("MyTLUServer.Domain.Models.Major", b =>
                {
                    b.Property<string>("MajorCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("major_code");

                    b.Property<string>("DeptCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("dept_code");

                    b.Property<string>("MajorName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("major_name");

                    b.HasKey("MajorCode")
                        .HasName("PK__majors__0D732CA0B387A0D5");

                    b.HasIndex("DeptCode");

                    b.HasIndex(new[] { "MajorName" }, "UQ__majors__B2815F7AA8862F7D")
                        .IsUnique();

                    b.ToTable("majors");
                });

            modelBuilder.Entity("MyTLUServer.Domain.Models.Student", b =>
                {
                    b.Property<string>("StudentCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("student_code");

                    b.Property<string>("AcademicStatus")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("academic_status");

                    b.Property<string>("AcademicStatus1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("academic_status_1");

                    b.Property<string>("AdminClass")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("admin_class");

                    b.Property<string>("AdmissionDecision")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("admission_decision");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("gender");

                    b.Property<string>("IntakeYear")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("intake_year");

                    b.Property<string>("MajorName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("major_name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.HasKey("StudentCode")
                        .HasName("PK__students__6DF33C44888D9674");

                    b.ToTable("students");
                });

            modelBuilder.Entity("MyTLUServer.Domain.Models.StudentDetail", b =>
                {
                    b.Property<string>("StudentCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("student_code");

                    b.Property<string>("ContactAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("contact_address");

                    b.Property<string>("Ethnicity")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ethnicity");

                    b.Property<string>("FatherFullName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("father_full_name");

                    b.Property<string>("FatherPhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("father_phone_number");

                    b.Property<string>("MotherFullName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mother_full_name");

                    b.Property<string>("MotherPhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("mother_phone_number");

                    b.Property<string>("Religion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("religion");

                    b.HasKey("StudentCode")
                        .HasName("PK__student___6DF33C449A1AB826");

                    b.ToTable("student_details");
                });

            modelBuilder.Entity("MyTLUServer.Domain.Models.StudentIdentification", b =>
                {
                    b.Property<string>("StudentCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("student_code");

                    b.Property<DateOnly?>("IdIssueDate")
                        .HasColumnType("date")
                        .HasColumnName("id_issue_date");

                    b.Property<string>("IdIssuePlace")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id_issue_place");

                    b.Property<string>("NationalId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("national_id");

                    b.Property<string>("PlaceOfBirth")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("place_of_birth");

                    b.HasKey("StudentCode")
                        .HasName("PK__student___6DF33C44764F526B");

                    b.ToTable("student_identification");
                });

            modelBuilder.Entity("MyTLUServer.Domain.Models.Subject", b =>
                {
                    b.Property<string>("SubjectCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("subject_code");

                    b.Property<int>("Credits")
                        .HasColumnType("int")
                        .HasColumnName("credits");

                    b.Property<string>("DeptCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("dept_code");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int?>("SessionDurationMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(90)
                        .HasColumnName("session_duration_minutes");

                    b.Property<int?>("SessionsPerWeek")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("sessions_per_week");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("subject_name");

                    b.HasKey("SubjectCode")
                        .HasName("PK__subjects__CEACD92125372766");

                    b.HasIndex("DeptCode");

                    b.ToTable("subjects");
                });

            modelBuilder.Entity("MyTLUServer.Domain.Models.AttendanceRecord", b =>
                {
                    b.HasOne("MyTLUServer.Domain.Models.ClassSession", "ClassSession")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("ClassSessionId")
                        .HasConstraintName("FK__attendanc__class__74AE54BC");

                    b.HasOne("MyTLUServer.Domain.Models.Student", "StudentCodeNavigation")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("StudentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__attendanc__stude__75A278F5");

                    b.Navigation("ClassSession");

                    b.Navigation("StudentCodeNavigation");
                });

            modelBuilder.Entity("MyTLUServer.Domain.Models.Class", b =>
                {
                    b.HasOne("MyTLUServer.Domain.Models.Lecturer", "LecturerCodeNavigation")
                        .WithMany("Classes")
                        .HasForeignKey("LecturerCode")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__classes__lecture__66603565");

                    b.HasOne("MyTLUServer.Domain.Models.Subject", "SubjectCodeNavigation")
                        .WithMany("Classes")
                        .HasForeignKey("SubjectCode")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__classes__subject__656C112C");

                    b.Navigation("LecturerCodeNavigation");

                    b.Navigation("SubjectCodeNavigation");
                });

            modelBuilder.Entity("MyTLUServer.Domain.Models.ClassSession", b =>
                {
                    b.HasOne("MyTLUServer.Domain.Models.Class", "ClassCodeNavigation")
                        .WithMany("ClassSessions")
                        .HasForeignKey("ClassCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__class_ses__class__6FE99F9F");

                    b.Navigation("ClassCodeNavigation");
                });

            modelBuilder.Entity("MyTLUServer.Domain.Models.Curriculum", b =>
                {
                    b.HasOne("MyTLUServer.Domain.Models.Major", "MajorCodeNavigation")
                        .WithMany("Curricula")
                        .HasForeignKey("MajorCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__curriculu__major__5FB337D6");

                    b.HasOne("MyTLUServer.Domain.Models.Subject", "SubjectCodeNavigation")
                        .WithMany("Curricula")
                        .HasForeignKey("SubjectCode")
                        .IsRequired()
                        .HasConstraintName("FK__curriculu__subje__60A75C0F");

                    b.Navigation("MajorCodeNavigation");

                    b.Navigation("SubjectCodeNavigation");
                });

            modelBuilder.Entity("MyTLUServer.Domain.Models.Department", b =>
                {
                    b.HasOne("MyTLUServer.Domain.Models.Faculty", "FacultyCodeNavigation")
                        .WithMany("Departments")
                        .HasForeignKey("FacultyCode")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__departmen__facul__4316F928");

                    b.Navigation("FacultyCodeNavigation");
                });

            modelBuilder.Entity("MyTLUServer.Domain.Models.Enrollment", b =>
                {
                    b.HasOne("MyTLUServer.Domain.Models.Class", "ClassCodeNavigation")
                        .WithMany("Enrollments")
                        .HasForeignKey("ClassCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__enrollmen__class__6C190EBB");

                    b.HasOne("MyTLUServer.Domain.Models.Student", "StudentCodeNavigation")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__enrollmen__stude__6B24EA82");

                    b.Navigation("ClassCodeNavigation");

                    b.Navigation("StudentCodeNavigation");
                });

            modelBuilder.Entity("MyTLUServer.Domain.Models.FaceDatum", b =>
                {
                    b.HasOne("MyTLUServer.Domain.Models.Student", "StudentCodeNavigation")
                        .WithMany("FaceData")
                        .HasForeignKey("StudentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__face_data__stude__7B5B524B");

                    b.Navigation("StudentCodeNavigation");
                });

            modelBuilder.Entity("MyTLUServer.Domain.Models.Lecturer", b =>
                {
                    b.HasOne("MyTLUServer.Domain.Models.Department", "DeptCodeNavigation")
                        .WithMany("Lecturers")
                        .HasForeignKey("DeptCode")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__lecturers__dept___47DBAE45");

                    b.HasOne("MyTLUServer.Domain.Models.Login", "LecturerCodeNavigation")
                        .WithOne("Lecturer")
                        .HasForeignKey("MyTLUServer.Domain.Models.Lecturer", "LecturerCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__lecturers__lectu__46E78A0C");

                    b.Navigation("DeptCodeNavigation");

                    b.Navigation("LecturerCodeNavigation");
                });

            modelBuilder.Entity("MyTLUServer.Domain.Models.Major", b =>
                {
                    b.HasOne("MyTLUServer.Domain.Models.Department", "DeptCodeNavigation")
                        .WithMany("Majors")
                        .HasForeignKey("DeptCode")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__majors__dept_cod__5535A963");

                    b.Navigation("DeptCodeNavigation");
                });

            modelBuilder.Entity("MyTLUServer.Domain.Models.Student", b =>
                {
                    b.HasOne("MyTLUServer.Domain.Models.Login", "StudentCodeNavigation")
                        .WithOne("Student")
                        .HasForeignKey("MyTLUServer.Domain.Models.Student", "StudentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__students__studen__4BAC3F29");

                    b.Navigation("StudentCodeNavigation");
                });

            modelBuilder.Entity("MyTLUServer.Domain.Models.StudentDetail", b =>
                {
                    b.HasOne("MyTLUServer.Domain.Models.Student", "StudentCodeNavigation")
                        .WithOne("StudentDetail")
                        .HasForeignKey("MyTLUServer.Domain.Models.StudentDetail", "StudentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__student_d__stude__5165187F");

                    b.Navigation("StudentCodeNavigation");
                });

            modelBuilder.Entity("MyTLUServer.Domain.Models.StudentIdentification", b =>
                {
                    b.HasOne("MyTLUServer.Domain.Models.Student", "StudentCodeNavigation")
                        .WithOne("StudentIdentification")
                        .HasForeignKey("MyTLUServer.Domain.Models.StudentIdentification", "StudentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__student_i__stude__4E88ABD4");

                    b.Navigation("StudentCodeNavigation");
                });

            modelBuilder.Entity("MyTLUServer.Domain.Models.Subject", b =>
                {
                    b.HasOne("MyTLUServer.Domain.Models.Department", "DeptCodeNavigation")
                        .WithMany("Subjects")
                        .HasForeignKey("DeptCode")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__subjects__dept_c__59FA5E80");

                    b.Navigation("DeptCodeNavigation");
                });

            modelBuilder.Entity("MyTLUServer.Domain.Models.Class", b =>
                {
                    b.Navigation("ClassSessions");

                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("MyTLUServer.Domain.Models.ClassSession", b =>
                {
                    b.Navigation("AttendanceRecords");
                });

            modelBuilder.Entity("MyTLUServer.Domain.Models.Department", b =>
                {
                    b.Navigation("Lecturers");

                    b.Navigation("Majors");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("MyTLUServer.Domain.Models.Faculty", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("MyTLUServer.Domain.Models.Lecturer", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("MyTLUServer.Domain.Models.Login", b =>
                {
                    b.Navigation("Lecturer");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MyTLUServer.Domain.Models.Major", b =>
                {
                    b.Navigation("Curricula");
                });

            modelBuilder.Entity("MyTLUServer.Domain.Models.Student", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("Enrollments");

                    b.Navigation("FaceData");

                    b.Navigation("StudentDetail");

                    b.Navigation("StudentIdentification");
                });

            modelBuilder.Entity("MyTLUServer.Domain.Models.Subject", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Curricula");
                });
#pragma warning restore 612, 618
        }
    }
}
